# Generated by Django 3.0.8 on 2020-09-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='userType',
            new_name='user_type',
        ),
    ]
